---
functional:
 - Пользователь имеет возможность соревноваться с другим игроком или ботом
 - Пользователь имеет возможность соревновать с другом по приглашению
 - Пользователь имеет возможность выбрать уровень сложности игры
 - Пользователь имеет возможность выбрать язык игры после начала игры
 - Пользователь имеет возможность проверять свое решение любое количество раз
 - Пользователь имеет возможность переподключиться к игре в любой момент пока она не закончена
 - Пользователь имеет возможность выбрать рандомную или определенную игру
 - Пользователь имеет возможность видеть написание кода у себя и у соперника
 - Пользователь имеет возможность просматривать рейтинги игроков
 - Пользователь имеет возможность выбрать язык программирования для решения задачи
 - Пользователь имеет возможность изменить язык прграммирования во время решения задачи
 - Пользователь имеет возможность видеть вывод тестов у себя и у соперника
 - Пользователь имеет возможность следить за ходом игры других игроков
 - Зарегистрированный пользователь имеет возможность общаться в чате
 - Задачи формулируются на русском и на английском языке
 - Завершенная игра доступна в записи
 - Игра может длиться неограниченное время
 - По результатам игры пользователь получает очки рейтинга
 - Пользователь считается победителем если он первым решит задачу (удовлетворит тестам)
 - Победитель-игрок может выйти из игры по нажатию кнопки "exit", которая у него появилась
 - У победителя-игрока после победы кнопка "check" становится неактивной 
 - Победитель-игрок после победы может остаться и посмотреть ещё раз на свой код
 - Побежденный соперник после объявление результата может выйти или доиграть до конца
 - Когда оба игрока вышли, игра считается полностью законченной и удаляется из памяти
non-functional:
 - Сайт должен быть разработан с учетом удобства использования
 - Сайт долежн быть оптимизирован для скорости работы
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен быть удобным на мобильном устройстве
 - Сайт должен быть совместимым с последними версиями браузеров
 - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
 - В чате установлено ограничение длины сообщения
 - В чате есть возможность использовать только текст и добавленные эмодзи
 - В случае превышения длины сообщения в чаты появляется уведомление
 - Отображается список пользователей онлайн
 - Пользователям из списка онлайн можно отправить приглашение в игру
 - В истории игр отображается информация об игре: дата и время, игроки, уровень сложности
